builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/plugin
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
    - "conventionxtreme/{{ .ProjectName }}:{{ .Version }}-amd64"
    dockerfile: build/linux-amd64.Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/convention-x-treme/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/convention-x-treme/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
    - "conventionxtreme/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    goarch: arm64
    dockerfile: build/linux-arm64.Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/arm64/v8
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/convention-x-treme/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/convention-x-treme/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
    - "conventionxtreme/{{ .ProjectName }}:{{ .Version }}-arm32v7"
    goarch: arm
    dockerfile: build/linux-arm.Dockerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/arm32/v7
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/convention-x-treme/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/convention-x-treme/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  - name_template: conventionxtreme/{{ .ProjectName }}:{{ .Version }}
    image_templates:
    - "conventionxtreme/{{ .ProjectName }}:{{ .Version }}-amd64"
    - "conventionxtreme/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    - "conventionxtreme/{{ .ProjectName }}:{{ .Version }}-arm32v7"
  - name_template: conventionxtreme/{{ .ProjectName }}:latest
    image_templates:
    - "conventionxtreme/{{ .ProjectName }}:{{ .Version }}-amd64"
    - "conventionxtreme/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    - "conventionxtreme/{{ .ProjectName }}:{{ .Version }}-arm32v7"
